# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Sat Nov 13 17:37:30 2010
#      by: PyQt4 UI code generator 4.8
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(743, 559)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnVuelos = QtGui.QPushButton(self.groupBox)
        self.btnVuelos.setObjectName(_fromUtf8("btnVuelos"))
        self.horizontalLayout.addWidget(self.btnVuelos)
        self.btnInstanciasVuelos = QtGui.QPushButton(self.groupBox)
        self.btnInstanciasVuelos.setObjectName(_fromUtf8("btnInstanciasVuelos"))
        self.horizontalLayout.addWidget(self.btnInstanciasVuelos)
        self.verticalLayout.addWidget(self.groupBox)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.Instanciasdevuelo = QtGui.QWidget()
        self.Instanciasdevuelo.setObjectName(_fromUtf8("Instanciasdevuelo"))
        self.gridLayout = QtGui.QGridLayout(self.Instanciasdevuelo)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.Instanciasdevuelo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btnAgregarInstVuelos = QtGui.QPushButton(self.frame)
        self.btnAgregarInstVuelos.setObjectName(_fromUtf8("btnAgregarInstVuelos"))
        self.gridLayout_2.addWidget(self.btnAgregarInstVuelos, 0, 0, 1, 1)
        self.btnModificarInstVuelos = QtGui.QPushButton(self.frame)
        self.btnModificarInstVuelos.setObjectName(_fromUtf8("btnModificarInstVuelos"))
        self.gridLayout_2.addWidget(self.btnModificarInstVuelos, 0, 1, 1, 1)
        self.btnEliminarInstVuelos = QtGui.QPushButton(self.frame)
        self.btnEliminarInstVuelos.setObjectName(_fromUtf8("btnEliminarInstVuelos"))
        self.gridLayout_2.addWidget(self.btnEliminarInstVuelos, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.frame, 3, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(self.Instanciasdevuelo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(500, 300))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.calendarioVuelos = QtGui.QCalendarWidget(self.groupBox_2)
        self.calendarioVuelos.setMaximumSize(QtCore.QSize(250, 200))
        self.calendarioVuelos.setObjectName(_fromUtf8("calendarioVuelos"))
        self.horizontalLayout_4.addWidget(self.calendarioVuelos)
        self.tablaSalidas = QtGui.QTableView(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tablaSalidas.sizePolicy().hasHeightForWidth())
        self.tablaSalidas.setSizePolicy(sizePolicy)
        self.tablaSalidas.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tablaSalidas.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablaSalidas.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablaSalidas.setCornerButtonEnabled(False)
        self.tablaSalidas.setObjectName(_fromUtf8("tablaSalidas"))
        self.tablaSalidas.horizontalHeader().setCascadingSectionResizes(True)
        self.tablaSalidas.horizontalHeader().setDefaultSectionSize(200)
        self.tablaSalidas.horizontalHeader().setStretchLastSection(True)
        self.tablaSalidas.verticalHeader().setVisible(False)
        self.tablaSalidas.verticalHeader().setCascadingSectionResizes(False)
        self.tablaSalidas.verticalHeader().setDefaultSectionSize(30)
        self.tablaSalidas.verticalHeader().setMinimumSectionSize(20)
        self.tablaSalidas.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_4.addWidget(self.tablaSalidas)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 3, 2)
        self.stackedWidget.addWidget(self.Instanciasdevuelo)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.page_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tablaVuelos = QtGui.QTableView(self.groupBox_3)
        self.tablaVuelos.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablaVuelos.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablaVuelos.setCornerButtonEnabled(False)
        self.tablaVuelos.setObjectName(_fromUtf8("tablaVuelos"))
        self.tablaVuelos.horizontalHeader().setCascadingSectionResizes(True)
        self.tablaVuelos.horizontalHeader().setDefaultSectionSize(200)
        self.tablaVuelos.horizontalHeader().setHighlightSections(False)
        self.tablaVuelos.horizontalHeader().setStretchLastSection(True)
        self.tablaVuelos.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.tablaVuelos, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.frame_3 = QtGui.QFrame(self.page_2)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnAgregarVuelo = QtGui.QPushButton(self.frame_3)
        self.btnAgregarVuelo.setObjectName(_fromUtf8("btnAgregarVuelo"))
        self.horizontalLayout_3.addWidget(self.btnAgregarVuelo)
        self.btnModificarVuelo = QtGui.QPushButton(self.frame_3)
        self.btnModificarVuelo.setObjectName(_fromUtf8("btnModificarVuelo"))
        self.horizontalLayout_3.addWidget(self.btnModificarVuelo)
        self.btnEliminarVuelo = QtGui.QPushButton(self.frame_3)
        self.btnEliminarVuelo.setObjectName(_fromUtf8("btnEliminarVuelo"))
        self.horizontalLayout_3.addWidget(self.btnEliminarVuelo)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 743, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMen = QtGui.QMenu(self.menubar)
        self.menuMen.setObjectName(_fromUtf8("menuMen"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionDesloguearse = QtGui.QAction(MainWindow)
        self.actionDesloguearse.setObjectName(_fromUtf8("actionDesloguearse"))
        self.actionAcerca_de = QtGui.QAction(MainWindow)
        self.actionAcerca_de.setObjectName(_fromUtf8("actionAcerca_de"))
        self.menuMen.addAction(self.actionDesloguearse)
        self.menuMen.addSeparator()
        self.menuMen.addAction(self.actionAcerca_de)
        self.menubar.addAction(self.menuMen.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "svr - Sistema de Vuelos y Reservas", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Administración", None, QtGui.QApplication.UnicodeUTF8))
        self.btnVuelos.setText(QtGui.QApplication.translate("MainWindow", "Vuelos", None, QtGui.QApplication.UnicodeUTF8))
        self.btnInstanciasVuelos.setText(QtGui.QApplication.translate("MainWindow", "Instancias de vuelos", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAgregarInstVuelos.setText(QtGui.QApplication.translate("MainWindow", "Agregar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnModificarInstVuelos.setText(QtGui.QApplication.translate("MainWindow", "Modificar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEliminarInstVuelos.setText(QtGui.QApplication.translate("MainWindow", "Eliminar", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Instancias de vuelos", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Vuelos", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAgregarVuelo.setText(QtGui.QApplication.translate("MainWindow", "Agregar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnModificarVuelo.setText(QtGui.QApplication.translate("MainWindow", "Modificar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEliminarVuelo.setText(QtGui.QApplication.translate("MainWindow", "Eliminar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMen.setTitle(QtGui.QApplication.translate("MainWindow", "Menú", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDesloguearse.setText(QtGui.QApplication.translate("MainWindow", "Acerca de...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAcerca_de.setText(QtGui.QApplication.translate("MainWindow", "Salir", None, QtGui.QApplication.UnicodeUTF8))

